### ALL CARS
GET http://localhost:3000/api/v1/cars

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?brand=ar

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?year=2019

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?year=2019&brand=Marca

### FIND CARS
GET http://localhost:3000/api/v1/cars/10

### CREATE CAR
POST http://localhost:3000/api/v1/cars
Content-Type: application/json

{
  "brand": "Marca",
  "model": "Modelo",
  "year": 2018,
  "plate": "BBC-1D01"
}

> {% client.global.set("carId", response.body.id); %}

### CREATE ITENS
POST http://localhost:3000/api/v1/cars/76/items
Content-Type: application/json

  [
    "Ar condicionado",
    "Trava Eletrica",
    "Vidro Eletrico"
  ]

### UPDATE CAR
PATCH http://localhost:3000/api/v1/cars/10
Content-type: application/json

{
  "brand": "Marca",
  "model": "Modelo",
  "year": 2080
}

### DELETE CAR
DELETE http://localhost:3000/api/v1/cars/4