### REGISTER USER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Diogo",
  "email": "Vasconcelos@compasso.pb.br",
  "password": "12345678"
}

### ALL CARS
GET http://localhost:3000/api/v1/cars

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?brand=ar

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?year=2019

### ALL CARS WITH FILTER
GET http://localhost:3000/api/v1/cars?year=2019&brand=Marca

### FIND CARS
GET http://localhost:3000/api/v1/cars/10

### CREATE CAR
POST http://localhost:3000/api/v1/cars
Content-Type: application/json

{
  "brand": "Marca",
  "model": "Modelo",
  "year": 2058,
  "plate": "ABC-1D01"
}

> {% client.global.set("carId", response.body.id); %}

### CREATE ITENS
POST http://localhost:3000/api/v1/cars/{{carId}}/items
Content-Type: application/json

  [
    "Ar condicionado",
    "Trava Eletrica",
    "Vidro Eletrico"
  ]

### UPDATE CAR
PATCH http://localhost:3000/api/v1/cars/100
Content-type: application/json

{
  "brand": "Marca",
  "model": "Modelo",
  "year": 2080
}

### DELETE CAR
DELETE http://localhost:3000/api/v1/cars/4